spring.application.name=MyPickCafe

## =====================
## Oracle DB
## =====================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=jspuser
spring.datasource.password=jsp2025
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

## =====================
## H2 DB (임시)
## =====================
#spring.datasource.url=jdbc:h2:mem:MyPickCafedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=never

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

## =====================
## JPA & Hibernate ??
## =====================
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100

## =====================
## JSON / TimeZone
## =====================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.time-zone=Asia/Seoul

## =====================
## ?? ?? ??
## =====================
server.error.include-message=ALWAYS
server.error.include-binding-errors=ALWAYS
server.error.include-stacktrace=ALWAYS

## =====================
## ?? ?? ??
## =====================
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false

## =====================
## ?? ??? / ?? ??
## =====================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB
spring.web.resources.static-locations=classpath:/static/
file.upload-dir=./uploads

## =====================
## ???
## =====================
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

## =====================
## Mustache ???
## =====================
spring.mustache.prefix=classpath:/templates/
spring.mustache.suffix=.mustache
spring.mustache.check-template-location=true

## =====================
## ??
## =====================
logging.level.org.hibernate.SQL=WARN
logging.level.org.springframework.security=DEBUG
logging.level.com.example.MyPickCafe.security=DEBUG

## =====================
## JWT ??
## =====================
app.jwt.secret=b+QWlwcbxeaYvCWDVr4SCzdG0iGa1txCsdMLa7H0U3A=
app.jwt.expiration-ms=3600000

## =====================
## ??? API ?
## =====================
kakao.js-key=${KAKAO_JS_KEY:}
kakao.rest-key=${KAKAO_REST_KEY:}

## =====================
## Python AI API
## =====================
python.api.base-url=http://localhost:8000
